backend:
  name: github
  repo: AviFried/itschill
  branch: main



media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Media"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{date}} {{image}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Video URL (YouTube/Vimeo)", name: "video", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "hidden", required: false}
